// source: cs3/ocm/provider/v1beta1/resources.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.cs3.ocm.provider.v1beta1.ProviderInfo', null, global);
goog.exportSymbol('proto.cs3.ocm.provider.v1beta1.Service', null, global);
goog.exportSymbol('proto.cs3.ocm.provider.v1beta1.ServiceEndpoint', null, global);
goog.exportSymbol('proto.cs3.ocm.provider.v1beta1.ServiceType', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.ocm.provider.v1beta1.ServiceType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.ocm.provider.v1beta1.ServiceType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.ocm.provider.v1beta1.ServiceType.displayName = 'proto.cs3.ocm.provider.v1beta1.ServiceType';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.cs3.ocm.provider.v1beta1.ServiceEndpoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.displayName = 'proto.cs3.ocm.provider.v1beta1.ServiceEndpoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.ocm.provider.v1beta1.Service = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.ocm.provider.v1beta1.Service.repeatedFields_, null);
};
goog.inherits(proto.cs3.ocm.provider.v1beta1.Service, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.ocm.provider.v1beta1.Service.displayName = 'proto.cs3.ocm.provider.v1beta1.Service';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.cs3.ocm.provider.v1beta1.ProviderInfo.repeatedFields_, null);
};
goog.inherits(proto.cs3.ocm.provider.v1beta1.ProviderInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.cs3.ocm.provider.v1beta1.ProviderInfo.displayName = 'proto.cs3.ocm.provider.v1beta1.ProviderInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.ocm.provider.v1beta1.ServiceType.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.ocm.provider.v1beta1.ServiceType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.ServiceType.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceType}
 */
proto.cs3.ocm.provider.v1beta1.ServiceType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.ocm.provider.v1beta1.ServiceType;
  return proto.cs3.ocm.provider.v1beta1.ServiceType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceType}
 */
proto.cs3.ocm.provider.v1beta1.ServiceType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.ocm.provider.v1beta1.ServiceType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.ocm.provider.v1beta1.ServiceType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.ServiceType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ServiceType.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceType} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceType.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ServiceType.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceType} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceType.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: (f = msg.getType()) && proto.cs3.ocm.provider.v1beta1.ServiceType.toObject(includeInstance, f),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    path: jspb.Message.getFieldWithDefault(msg, 3, ""),
    isMonitored: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    propertiesMap: (f = msg.getPropertiesMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.ocm.provider.v1beta1.ServiceEndpoint;
  return proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.cs3.ocm.provider.v1beta1.ServiceType;
      reader.readMessage(value,proto.cs3.ocm.provider.v1beta1.ServiceType.deserializeBinaryFromReader);
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPath(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsMonitored(value);
      break;
    case 5:
      var value = msg.getPropertiesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.cs3.ocm.provider.v1beta1.ServiceType.serializeBinaryToWriter
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getIsMonitored();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getPropertiesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(5, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional ServiceType type = 1;
 * @return {?proto.cs3.ocm.provider.v1beta1.ServiceType}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.getType = function() {
  return /** @type{?proto.cs3.ocm.provider.v1beta1.ServiceType} */ (
    jspb.Message.getWrapperField(this, proto.cs3.ocm.provider.v1beta1.ServiceType, 1));
};


/**
 * @param {?proto.cs3.ocm.provider.v1beta1.ServiceType|undefined} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
*/
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.setType = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.clearType = function() {
  return this.setType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string path = 3;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.getPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.setPath = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bool is_monitored = 4;
 * @return {boolean}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.getIsMonitored = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.setIsMonitored = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * map<string, string> properties = 5;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.getPropertiesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 5, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} returns this
 */
proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.prototype.clearPropertiesMap = function() {
  this.getPropertiesMap().clear();
  return this;};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.ocm.provider.v1beta1.Service.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.ocm.provider.v1beta1.Service.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.ocm.provider.v1beta1.Service} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.Service.toObject = function(includeInstance, msg) {
  var f, obj = {
    host: jspb.Message.getFieldWithDefault(msg, 1, ""),
    endpoint: (f = msg.getEndpoint()) && proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.toObject(includeInstance, f),
    apiVersion: jspb.Message.getFieldWithDefault(msg, 3, ""),
    additionalEndpointsList: jspb.Message.toObjectList(msg.getAdditionalEndpointsList(),
    proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.ocm.provider.v1beta1.Service}
 */
proto.cs3.ocm.provider.v1beta1.Service.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.ocm.provider.v1beta1.Service;
  return proto.cs3.ocm.provider.v1beta1.Service.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.ocm.provider.v1beta1.Service} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.ocm.provider.v1beta1.Service}
 */
proto.cs3.ocm.provider.v1beta1.Service.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setHost(value);
      break;
    case 2:
      var value = new proto.cs3.ocm.provider.v1beta1.ServiceEndpoint;
      reader.readMessage(value,proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.deserializeBinaryFromReader);
      msg.setEndpoint(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiVersion(value);
      break;
    case 4:
      var value = new proto.cs3.ocm.provider.v1beta1.ServiceEndpoint;
      reader.readMessage(value,proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.deserializeBinaryFromReader);
      msg.addAdditionalEndpoints(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.ocm.provider.v1beta1.Service.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.ocm.provider.v1beta1.Service} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.Service.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHost();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEndpoint();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.serializeBinaryToWriter
    );
  }
  f = message.getApiVersion();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAdditionalEndpointsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.cs3.ocm.provider.v1beta1.ServiceEndpoint.serializeBinaryToWriter
    );
  }
};


/**
 * optional string host = 1;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.getHost = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.setHost = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ServiceEndpoint endpoint = 2;
 * @return {?proto.cs3.ocm.provider.v1beta1.ServiceEndpoint}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.getEndpoint = function() {
  return /** @type{?proto.cs3.ocm.provider.v1beta1.ServiceEndpoint} */ (
    jspb.Message.getWrapperField(this, proto.cs3.ocm.provider.v1beta1.ServiceEndpoint, 2));
};


/**
 * @param {?proto.cs3.ocm.provider.v1beta1.ServiceEndpoint|undefined} value
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
*/
proto.cs3.ocm.provider.v1beta1.Service.prototype.setEndpoint = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.clearEndpoint = function() {
  return this.setEndpoint(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.hasEndpoint = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string api_version = 3;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.getApiVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.setApiVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated ServiceEndpoint additional_endpoints = 4;
 * @return {!Array<!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint>}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.getAdditionalEndpointsList = function() {
  return /** @type{!Array<!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cs3.ocm.provider.v1beta1.ServiceEndpoint, 4));
};


/**
 * @param {!Array<!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint>} value
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
*/
proto.cs3.ocm.provider.v1beta1.Service.prototype.setAdditionalEndpointsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cs3.ocm.provider.v1beta1.ServiceEndpoint}
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.addAdditionalEndpoints = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.cs3.ocm.provider.v1beta1.ServiceEndpoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.ocm.provider.v1beta1.Service} returns this
 */
proto.cs3.ocm.provider.v1beta1.Service.prototype.clearAdditionalEndpointsList = function() {
  return this.setAdditionalEndpointsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.cs3.ocm.provider.v1beta1.ProviderInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    fullName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    organization: jspb.Message.getFieldWithDefault(msg, 4, ""),
    domain: jspb.Message.getFieldWithDefault(msg, 5, ""),
    homepage: jspb.Message.getFieldWithDefault(msg, 6, ""),
    email: jspb.Message.getFieldWithDefault(msg, 7, ""),
    servicesList: jspb.Message.toObjectList(msg.getServicesList(),
    proto.cs3.ocm.provider.v1beta1.Service.toObject, includeInstance),
    propertiesMap: (f = msg.getPropertiesMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.cs3.ocm.provider.v1beta1.ProviderInfo;
  return proto.cs3.ocm.provider.v1beta1.ProviderInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setFullName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrganization(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setDomain(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setHomepage(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 8:
      var value = new proto.cs3.ocm.provider.v1beta1.Service;
      reader.readMessage(value,proto.cs3.ocm.provider.v1beta1.Service.deserializeBinaryFromReader);
      msg.addServices(value);
      break;
    case 9:
      var value = msg.getPropertiesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readString, null, "", "");
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.cs3.ocm.provider.v1beta1.ProviderInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getFullName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getOrganization();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getDomain();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getHomepage();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getServicesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.cs3.ocm.provider.v1beta1.Service.serializeBinaryToWriter
    );
  }
  f = message.getPropertiesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(9, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeString);
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} returns this
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string full_name = 2;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.getFullName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} returns this
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.setFullName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} returns this
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string organization = 4;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.getOrganization = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} returns this
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.setOrganization = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string domain = 5;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.getDomain = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} returns this
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.setDomain = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string homepage = 6;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.getHomepage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} returns this
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.setHomepage = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string email = 7;
 * @return {string}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} returns this
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated Service services = 8;
 * @return {!Array<!proto.cs3.ocm.provider.v1beta1.Service>}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.getServicesList = function() {
  return /** @type{!Array<!proto.cs3.ocm.provider.v1beta1.Service>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.cs3.ocm.provider.v1beta1.Service, 8));
};


/**
 * @param {!Array<!proto.cs3.ocm.provider.v1beta1.Service>} value
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} returns this
*/
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.setServicesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.cs3.ocm.provider.v1beta1.Service=} opt_value
 * @param {number=} opt_index
 * @return {!proto.cs3.ocm.provider.v1beta1.Service}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.addServices = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.cs3.ocm.provider.v1beta1.Service, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} returns this
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.clearServicesList = function() {
  return this.setServicesList([]);
};


/**
 * map<string, string> properties = 9;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,string>}
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.getPropertiesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,string>} */ (
      jspb.Message.getMapField(this, 9, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.cs3.ocm.provider.v1beta1.ProviderInfo} returns this
 */
proto.cs3.ocm.provider.v1beta1.ProviderInfo.prototype.clearPropertiesMap = function() {
  this.getPropertiesMap().clear();
  return this;};


goog.object.extend(exports, proto.cs3.ocm.provider.v1beta1);
