version: "3.8"

volumes:
    api_node_modules:
        driver: local
    ui_node_modules:
        driver: local

services:
    db:
        image: postgres:13-alpine
        hostname: db
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            POSTGRES_DB: "describo"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            PGDATA: /postgresql/data
            CHOKIDAR_USEPOLLING: "true"
        # volumes:
        #     - describo_online_db_test:/postgresql
        ports:
            - 5432:5432

    api:
        image: node:14-stretch
        hostname: api
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "admin"
            DB_PASSWORD: "admin"
            DB_DATABASE: "describo"
        volumes:
            - ./api:/srv/api:delegated
            - ./.git:/srv/api/.git:delegated
            - api_node_modules:/srv/api/node_modules:delegated
            - ./configuration:/srv/configuration
            -   ../reva/:/srv/reva
        working_dir: /srv/api
        entrypoint: ['/bin/bash', './scripts/wait-for-postgres2.sh']
        command: ["npm run develop"]

    ui:
        image: node:14-stretch
        hostname: ui
        tty: true
        ports:
            - "9000:9000"
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            CHOKIDAR_USEPOLLING: "true"
        volumes:
            - ./ui:/srv/ui:delegated
            - ./.git:/srv/ui/.git:delegated
            - ui_node_modules:/srv/ui/node_modules:delegated
            - ./../describo-ui-plugins:/srv/plugins:delegated
        working_dir: /srv/ui
        command: ["npm", "run", "serve"]
#        command: ["tail", "-f", "/dev/null"]

    reva:
        image: cs3org/revad
        hostname: reva
        tty: true
        ports:
            - 19000:19000
        volumes:
            -   ./configuration:/srv/configuration
            -   ../reva/:/srv/reva
        command: >
            bash -c "
                cp /srv/configuration/revad/* /etc/revad/ &
                revad -c /etc/revad/gateway.toml &
                revad -c /etc/revad/storage-home.toml &
                revad -c /etc/revad/storage-reva.toml
            "
#    edge:
#        image: nginx:latest
#        hostname: edge
#        tty: true
#        environment:
#            TERM: "xterm-256color"
#        volumes:
#            - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
#            - $PWD/production/wait-for-it.sh:/wait-for-it.sh
#        command: ["/wait-for-it.sh", "app:8080", "-t", "10", "--", "nginx", "-g", "daemon off;"]
#        ports:
#            - 9000:9000
