version: "2"

# volumes:
#     describo_online_db_test:
#         driver: local

services:
    db:
        image: postgres:13-alpine
        hostname: db
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            POSTGRES_DB: "describo"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            PGDATA: /postgresql/data
        # volumes:
        #     - describo_online_db_test:/postgresql
        ports:
            - 5432:5432

    api:
        image: node:14-stretch
        hostname: api
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "admin"
            DB_PASSWORD: "admin"
            DB_DATABASE: "describo"
        volumes:
            - $PWD/api:/srv:delegated
            - $PWD/.git:/srv/.git:delegated
        working_dir: /srv
        command: ["./scripts/wait-for-postgres.sh", "npm run develop"]
        ports:
            - 8080:8080
