FROM --platform=$TARGETPLATFORM node:14-buster-slim
WORKDIR /srv
RUN apt-get update && apt-get install -y postgresql-client ca-certificates
COPY api/ /srv/
RUN npm install
COPY scripts/wait-for-postgres.sh /srv/wait-for-postgres.sh
CMD [ "/srv/wait-for-postgres.sh", "node", "index.js" ]  
