version: "3.8"

volumes:
    api_node_modules:
        driver: local
    ui_node_modules:
        driver: local
    MINIO_VOLUME:
        driver: local

services:
    db:
        image: postgres:13-alpine
        hostname: db
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            POSTGRES_DB: "describo"
            POSTGRES_USER: "root"
            POSTGRES_PASSWORD: "root"
            PGDATA: /postgresql/data
        # volumes:
        #     - describo_online_db_test:/postgresql
        # ports:
        #     - 5432:5432

    minio:
        image: minio/minio:latest
        restart: always
        entrypoint: sh
        ports:
            - 10000:9000
            - 10001:10001
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio_pass
        entrypoint:
            bash -c 'mkdir -p /data/uploads && /opt/bin/minio server /data --console-address ":10001"'
        volumes:
            - MINIO_VOLUME:/data
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:10001/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3

    api:
        image: node:14-buster
        hostname: api
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "root"
            DB_PASSWORD: "root"
            DB_DATABASE: "describo"
        volumes:
            - ./api:/srv/api:delegated
            - ./configuration:/srv/configuration
            - .git:/srv/api/.git:delegated
            - api_node_modules:/srv/api/node_modules:delegated
            - ./scripts/wait-for-it.sh:/wait-for-it.sh
        working_dir: /srv/api
        command: ["/wait-for-it.sh", "db:5432", "-t", "10", "--", "npm", "run", "develop"]

    ui:
        image: node:14-buster
        hostname: ui
        tty: true
        environment:
            TERM: "xterm-256color"
            NODE_ENV: "development"
        volumes:
            - ./ui:/srv/ui:delegated
            - .git:/srv/ui/.git:delegated
            - ../describo-ui-plugins:/srv/ui/src/plugins:delegated
            - ui_node_modules:/srv/ui/node_modules:delegated
        working_dir: /srv/ui
        command: ["npm", "run", "develop"]

    edge:
        image: nginx:latest
        hostname: edge
        tty: true
        environment:
            TERM: "xterm-256color"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - ./scripts/wait-for-it.sh:/wait-for-it.sh
        command: ["/wait-for-it.sh", "app:8080", "-t", "10", "--", "nginx", "-g", "daemon off;"]
        ports:
            - 9000:9000
