version: "3.8"

volumes:
    database_volume:
        driver: local

services:
    db:
        image: postgres:13-alpine
        hostname: db
        tty: true
        environment:
            TERM: "xterm-256color"
            POSTGRES_DB: "describo"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "admin"
            PGDATA: /postgresql/data
        volumes:
            - database_volume:/postgresql

    api:
        image: utseresearch/describo-online-api:latest
        hostname: api
        tty: true
        environment:
            TERM: "xterm-256color"
            DB_HOST: "db"
            DB_PORT: "5432"
            DB_USER: "admin"
            DB_PASSWORD: "admin"
            DB_DATABASE: "describo"
        volumes:
            - $PWD/production-configuration.json:/srv/configuration.json

    ui:
        image: utseresearch/describo-online-ui:latest
        hostname: ui
        tty: true
        environment:
            TERM: "xterm-256color"
        volumes:
            - $PWD/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80