#!/bin/bash

curl --silent --output schema.org.jsonld https://schema.org/version/latest/schemaorg-current-http.jsonld
node write-types.js
rm schema.org.jsonld
cp types/type-definitions.json ../src/common/type-definitions.json
cp types/type-definitions-lookup.json ../src/common/type-definitions-lookup.json
rm -rf types